name: remote ssh command
on: [push, workflow_dispatch]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd meteo-toulouse-api 
            git pull 
            sudo docker stop meteo-toulouse-api || true && sudo docker rm meteo-toulouse-api || true
            cd ./server
            sudo docker image build -t meteo-toulouse-api .
            sudo docker container run --name meteo-toulouse-api -d -p ${{ secrets.PORT }}:3000 -v /root/meteo-toulouse-api/server/.env:/app/.env meteo-toulouse-api